#ifndef MARKOWITZPORTFOLIOOPTIMISER_BACKTESTRESULTS_H
#define MARKOWITZPORTFOLIOOPTIMISER_BACKTESTRESULTS_H

struct BacktestResults {
    double retOOS;
    double retIS;
    double varOOS;
    double varIS;
};

#endif //MARKOWITZPORTFOLIOOPTIMISER_BACKTESTRESULTS_H
